<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">WebUI.Plus</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
         <?php
         global $_G;
         if(!empty($_G['me']['username'])){
          echo '<a class="btn btn-success" href="/my">Show My Images</a>';
        }else{
          echo '<a class="nav-link" href="/signup">Sign Up</a>';
        }
        ?>
      </li>
      <li class="nav-item dropdown">


        <?php

        if(!empty($_G['me']['username'])){

          echo '<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">'.$_G['me']['username'].'</a>';
          echo '<ul class="dropdown-menu">';
          echo '<li><a class="dropdown-item" href="/my/">My</a></li>';
          echo '<li><a class="dropdown-item" href="/my/profile">Profile</a></li>';
          echo '<li><a class="dropdown-item" href="/my/draw">Draw Your Pictures ...</a></li>';
          echo '<li><a class="dropdown-item" href="/signin/logout">Sign Out</a></li>';
          echo '</ul>';

        }else{
          echo '<a class="nav-link" href="/signin">Sign In</a>';
        }
        ?>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled">Save Your webui-generated-images online, Automatically!</a>
      </li>
    </ul>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>