<?php $this->partial("partials/header"); ?>
<body class="<?php echo $body_class;?>">
	<div class="container">
		<div class="row">
			
			<?php $this->partial("partials/navbar"); ?>
			
		</div>


		<div class="row gx-1">
			<div class="col-xl-2">
				<div class="col-model">
					<?php $this->partial("partials/model-list"); ?>
				</div>
			</div>

			<div class="col-xl-1">
				<div class="col-user">
					<?php $this->partial("partials/user-list"); ?>
				</div>
			</div>

			<div class="col-xl-9">
				<div class="col-image">
					<?php echo $this->getContent(); ?>

				</div>
			</div>

		</div>


		<div class="row">
			<?php $this->partial("partials/footer"); ?>
			<?php global $_G; echo "<hr/> running time: ".round(microtime(true) - $_G['time_start'],4)*1000 ." ms";?>
			<br/>
			<img style="height:47!important;width:293!important;margin:2px;" src="https://s01.flagcounter.com/count2/m02K/bg_FFFFFF/txt_F77B1B/border_CCCCCC/columns_3/maxflags_6/viewers_3/labels_1/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0" />
		</div>
	</div>

</body>
</html>